version: '2'

services:
  replicaset-remote:
    container_name: replicaset-remote
    image: docker.io/bitnami/mongodb:4.4
    ports:
      - "28000:27017"
    volumes:
      - 'replicaset-remote-data:/bitnami/mongodb'
      - '/data/shard.key:/data/shard.key'
    environment:
      - MONGODB_EXTRA_FLAGS= --replSet=replicaset-remote --keyFile=/data/shard.key
    restart: always
    mem_limit: 10000m
    cpu_shares: 512
volumes:
  replicaset-remote-data:
    driver: local
